/*
 * OOPSy-DAISY's on-device UI: the oops-apps index page, rendered by the SDK webview.
 *
 * This is a thin wrapper of the same catalogue the website serves (project-oops.github.io/
 * oops-apps), not a second listing to maintain. The page renders from two live sources the site
 * itself publishes, merged here:
 *
 *   - `__oopsy_meta()`     -> the site's own apps.json (title, subtitle, kind, readiness status),
 *                             fetched on device from the Pages site. This is the card content.
 *   - `__oopsy_catalog()`  -> the rolling `latest-main` release assets (name + size), which say
 *                             which titles actually have a build to install, and how big it is.
 *
 * An app in apps.json with no matching release asset is shown but marked "no build yet", exactly
 * as the website does. Everything else keeps the index look adapted to a 2010-era renderer:
 *   - litehtml has no CSS grid, its flexbox miscomputes, and it gives table cells zero height here,
 *     so the card grid is inline-block cards (the one layout it lays out correctly), each with an
 *     inline-block icon tile beside inline-block text.
 *   - litehtml also computes element styles once at parse and does not re-apply a changed `style`
 *     or `class` attribute, so a view switch cannot hide one element and show another. Every screen
 *     is therefore rendered by replacing the single `#main` container's innerHTML, which re-parses.
 *
 * There is no mouse. The native controller (oopsy-daisy_main.c) reads the pad and keyboard and
 * drives the page by calling its functions through the JS engine: `oopsyNav(dir)` moves the
 * highlight, `oopsyCycleKind(d)` / `oopsyCycleStatus(d)` change the filters, `oopsyEnter()`
 * installs the highlighted title (the page calls back `__oopsy_install(name)`), `oopsyScreen()`
 * switches between the grid and the download queue and `oopsyRefresh()` repaints the queue. Install
 * is native - the page never touches the network or the filesystem.
 *
 * The markup is written with single-quoted HTML attributes and single-quoted JavaScript strings,
 * so the C string literal carries no escaped double-quotes. HTML built inside JS strings uses
 * \' for its attribute quotes.
 */

const char oopsy_page_html[] =
"<!doctype html>\n"
"<html lang='en'><head><meta charset='utf-8'>\n"
"<style>\n"
":root{--accent:#3fb950;--bg:#08090b;--panel:#111317;--panel2:#171a1f;--fg:#e9e9ea;--muted:#9aa0a6;--rule:#24272d}\n"
"*{box-sizing:border-box}\n"
"html,body{margin:0}\n"
"body{background:#08090b;color:#e9e9ea;font-family:monospace;line-height:1.5}\n"
".wrap{max-width:1640px;margin:0 auto;padding:0 32px}\n"
".site{padding:34px 0 16px;border-bottom:1px solid #24272d}\n"
".brand{font-size:30px;margin:0 0 12px;font-weight:700}\n"
".brand .b1,.brand .b2{display:inline-block;vertical-align:top}\n"
".brand .b2{color:#3fb950;margin-left:14px}\n"
".tagline{color:#9aa0a6;margin:0 0 16px;font-size:15px}\n"
".filters{margin:6px 0}\n"
".flabel{display:inline-block;color:#9aa0a6;font-size:11px;margin-right:10px;min-width:74px;text-transform:uppercase}\n"
".chip{display:inline-block;background:#111317;border:1px solid #24272d;color:#9aa0a6;padding:5px 14px;border-radius:999px;margin:0 6px 6px 0;font-size:13px}\n"
".chip.sel{background:#3fb950;color:#04120a;border-color:#3fb950;font-weight:700}\n"
"#main{padding:20px 0 40px}\n"
".grid{font-size:0}\n"
".card{display:inline-block;vertical-align:top;width:372px;height:172px;margin:0 14px 14px 0;background:#111317;border:1px solid #24272d;border-radius:14px;padding:16px;font-size:14px}\n"
".card.sel{border-color:#3fb950;background:#171a1f}\n"
".chead{margin-bottom:10px}\n"
".tile{display:inline-block;vertical-align:middle;width:56px;height:56px;border-radius:12px;text-align:center;line-height:56px;font-size:22px;font-weight:700;color:#04120a;background:#3fb950}\n"
".ticon{display:inline-block;vertical-align:middle;width:56px;height:56px;border-radius:12px;background:#0b0d10}\n"
".ctitle{display:inline-block;vertical-align:middle;margin:0 0 0 14px;font-size:18px;font-weight:600}\n"
".cdesc{margin:0 0 8px;color:#9aa0a6;font-size:13px}\n"
".meta{margin-top:2px}\n"
".badge{display:inline-block;font-size:11px;color:#9aa0a6;border:1px solid #24272d;border-radius:6px;padding:2px 7px;margin:0 5px 5px 0}\n"
".badge.status{font-weight:700}\n"
".badge.playable{color:#3fb950;border-color:#2c5a34}\n"
".badge.experimental{color:#d29922;border-color:#5c4a1e}\n"
".badge.wip{color:#8b949e;border-color:#30363d}\n"
".badge.dim{color:#6a6f76}\n"
".badge.ok{color:#3fb950;border-color:#2c5a34;font-weight:700}\n"
".empty{color:#9aa0a6;padding:24px 0}\n"
".section{font-size:20px;margin:4px 0 16px}\n"
".qrow{background:#111317;border:1px solid #24272d;border-radius:10px;padding:14px 16px;margin-bottom:12px}\n"
".qhead{margin-bottom:8px}\n"
".qname{font-size:15px}\n"
".qstate{font-size:13px;color:#9aa0a6;margin-left:12px}\n"
".qstate.downloading{color:#d29922}\n"
".qstate.done{color:#3fb950}\n"
".qstate.failed{color:#f85149}\n"
".bar{height:10px;background:#20242a;border-radius:6px;overflow:hidden}\n"
".fill{height:100%;background:#3fb950}\n"
".fill.failed{background:#f85149}\n"
".foot{border-top:1px solid #24272d;padding:14px 0;color:#9aa0a6;font-size:13px}\n"
".modalbg{position:fixed;left:0;top:0;width:100%;height:100%;background:rgba(4,5,7,0.82);padding:150px 24px 0}\n"
".modalbox{width:720px;max-width:100%;margin:0 auto;background:#111317;border:1px solid #30363d;border-radius:16px;padding:24px 28px}\n"
".modalbox h2{font-size:22px;margin:0 0 6px;color:#3fb950}\n"
".msub{color:#9aa0a6;font-size:13px;margin:0 0 18px}\n"
".merr{color:#ffb4ab;font-size:16px;line-height:1.6;margin:6px 0 4px}\n"
".mfoot{margin-top:18px;border-top:1px solid #24272d;padding-top:14px;color:#9aa0a6;font-size:13px}\n"
"</style></head>\n"
"<body><div class='wrap'>\n"
"<header class='site'>\n"
"<h1 class='brand'><span class='b1'>oops-apps</span><span class='b2'>index</span></h1>\n"
"<p class='tagline'>Open homebrew for Orbis and Prospero consoles, built with oops-sdk and oops-mesa. Rebuilt fresh from main - highlight a title and press X to install it onto this console.</p>\n"
"<div class='filters'><span class='flabel'>Kind</span><span id='kindbar'></span></div>\n"
"<div class='filters'><span class='flabel'>Readiness</span><span id='statusbar'></span></div>\n"
"</header>\n"
"<div id='main'></div>\n"
"<footer class='foot'><span id='hint'>D-pad move | X install | L1/R1 kind | L2/R2 readiness | [ ] downloads | O exit</span></footer>\n"
"</div>\n"
"<div id='modal'></div>\n"
"<script>\n"
"'use strict';\n"
"function DBG(m){try{console.log('PAGEDBG '+m);}catch(e){}}\n"
"function esc(s){return String(s==null?'':s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');}\n"
"function obytes(n){if(!n&&n!==0)return '';var u=['B','KB','MB','GB'],i=0;while(n>=1024&&i<u.length-1){n/=1024;i++;}return (i===0?n:n.toFixed(1))+' '+u[i];}\n"
"var COLS=4;\n"
"var HDR=235,CARDH=172,ROWH=186;\n"
"var STATUS_META={playable:{label:'Playable',rank:0},experimental:{label:'Experimental',rank:1},wip:{label:'WIP',rank:2}};\n"
"function statusKey(s){return STATUS_META[s]?s:'experimental';}\n"
"var __apps=[],__vis=[],__sel=0,__screen='browse',__err='';\n"
"var __kind='all',__status='all',__kindKeys=['all'],__statusKeys=['all'];\n"
"function callJSON(fn){try{return JSON.parse(String(fn()||'[]'));}catch(e){return [];}}\n"
"function buildApps(){\n"
"  var meta=[],cat=[];\n"
"  try{meta=callJSON(__oopsy_meta);}catch(e){DBG('meta call threw:'+e);}\n"
"  try{cat=callJSON(__oopsy_catalog);}catch(e){DBG('cat call threw:'+e);}\n"
"  DBG('buildApps meta='+meta.length+' cat='+cat.length);\n"
"  var byName={},i;for(i=0;i<cat.length;i++)byName[cat[i].name]=cat[i];\n"
"  var out=[];\n"
"  if(meta.length){\n"
"    for(i=0;i<meta.length;i++){var m=meta[i];var c=byName[m.name];\n"
"      out.push({name:m.name,title:m.title||m.name,subtitle:m.subtitle||'',kind:m.kind||'',status:statusKey(m.status),size:c?c.size:0,installable:!!c,queued:false,icon:m.icon?('https://project-oops.github.io/oops-apps/'+m.icon):''});}\n"
"  }else{\n"
"    for(i=0;i<cat.length;i++){out.push({name:cat[i].name,title:cat[i].name,subtitle:'',kind:'',status:'experimental',size:cat[i].size,installable:true,queued:false});}\n"
"  }\n"
"  return out;\n"
"}\n"
"function distinctKinds(){var seen={},k=[],i;for(i=0;i<__apps.length;i++){var v=__apps[i].kind;if(v&&!seen[v]){seen[v]=1;k.push(v);}}k.sort();return k;}\n"
"function presentStatuses(){var seen={},i;for(i=0;i<__apps.length;i++)seen[statusKey(__apps[i].status)]=1;var order=['playable','experimental','wip'],out=[],j;for(j=0;j<order.length;j++)if(seen[order[j]])out.push(order[j]);return out;}\n"
"function matches(a){if(__kind!=='all'&&a.kind!==__kind)return false;if(__status!=='all'&&statusKey(a.status)!==__status)return false;return true;}\n"
"function visible(){var l=[],i;for(i=0;i<__apps.length;i++)if(matches(__apps[i]))l.push(__apps[i]);l.sort(function(a,b){return String(a.title).localeCompare(String(b.title));});return l;}\n"
"function chipHtml(items,active){var h='',i;for(i=0;i<items.length;i++){var sel=items[i].key===active?' sel':'';h+='<span class=\\'chip'+sel+'\\'>'+esc(items[i].label)+'</span>';}return h;}\n"
"function renderChips(){\n"
"  var ki=[{key:'all',label:'All'}],ks=distinctKinds(),i;for(i=0;i<ks.length;i++)ki.push({key:ks[i],label:ks[i]});\n"
"  __kindKeys=[];for(i=0;i<ki.length;i++)__kindKeys.push(ki[i].key);\n"
"  var si=[{key:'all',label:'Any'}],ss=presentStatuses();for(i=0;i<ss.length;i++)si.push({key:ss[i],label:STATUS_META[ss[i]].label});\n"
"  __statusKeys=[];for(i=0;i<si.length;i++)__statusKeys.push(si[i].key);\n"
"  var kb=document.getElementById('kindbar');if(kb)kb.innerHTML=chipHtml(ki,__kind);\n"
"  var sb=document.getElementById('statusbar');if(sb)sb.innerHTML=chipHtml(si,__status);\n"
"}\n"
"function cardHtml(a,i){\n"
"  var letter=esc((a.title||a.name||'?').charAt(0).toUpperCase());\n"
"  var st=statusKey(a.status);\n"
"  var m='<span class=\\'badge status '+st+'\\'>'+STATUS_META[st].label+'</span>';\n"
"  if(a.kind)m+='<span class=\\'badge\\'>'+esc(a.kind)+'</span>';\n"
"  if(a.installable)m+='<span class=\\'badge\\'>'+esc(a.size?obytes(a.size):'title')+'</span>';\n"
"  else m+='<span class=\\'badge dim\\'>no build yet</span>';\n"
"  if(a.queued)m+='<span class=\\'badge ok\\'>queued</span>';\n"
"  var st2=a.subtitle||'';if(st2.length>64)st2=st2.substring(0,62)+'..';var sub=st2?'<p class=\\'cdesc\\'>'+esc(st2)+'</p>':'';\n"
"  var tile=a.icon?('<img class=\\'ticon\\' src=\\''+esc(a.icon)+'\\'>'):('<div class=\\'tile\\'>'+letter+'</div>');\n"
"  var selc=(i===__sel)?'card sel':'card';\n"
"  return '<div class=\\''+selc+'\\' id=\\'card-'+i+'\\'><div class=\\'chead\\'>'+tile+'<h3 class=\\'ctitle\\'>'+esc(a.title||a.name)+'</h3></div>'+sub+'<div class=\\'meta\\'>'+m+'</div></div>';\n"
"}\n"
"function gridHtml(list){var h='',i;for(i=0;i<list.length;i++)h+=cardHtml(list[i],i);return h;}\n"
"function modalJobsHtml(){\n"
"  var jobs=callJSON(__oopsy_queue),h='',i;\n"
"  DBG('refresh jobs='+jobs.length+(jobs.length?(' '+jobs[0].state+' '+(jobs[0].pct|0)+'%'+(jobs[0].error?(' '+jobs[0].error):'')):''));\n"
"  h='<h2>Downloads</h2><p class=\\'msub\\'>Installing onto this console.</p>';\n"
"  if(!jobs.length)h+='<p class=\\'empty\\'>Nothing queued yet.</p>';\n"
"  for(i=0;i<jobs.length;i++){var j=jobs[i];\n"
"    var label=j.state;if(j.state==='failed'&&j.error)label=j.error;else if(j.state==='done')label='installed';else if(j.state==='downloading')label='downloading '+(j.pct|0)+'%';\n"
"    var pct=(j.pct|0);if(pct<0)pct=0;if(pct>100)pct=100;\n"
"    var ff=(j.state==='failed')?'fill failed':'fill';\n"
"    h+='<div class=\\'qrow\\'><div class=\\'qhead\\'><span class=\\'qname\\'>'+esc(j.name)+'</span><span class=\\'qstate '+esc(j.state)+'\\'>'+esc(label)+'</span></div><div class=\\'bar\\'><div class=\\''+ff+'\\' style=\\'width:'+pct+'%\\'></div></div></div>';\n"
"  }\n"
"  h+='<div class=\\'mfoot\\'>O back to apps</div>';\n"
"  return h;\n"
"}\n"
"function renderModal(){\n"
"  var m=document.getElementById('modal');if(!m)return;\n"
"  if(__err){m.innerHTML='<div class=\\'modalbg\\'><div class=\\'modalbox\\'><h2>No build yet</h2><p class=\\'merr\\'>'+esc(__err)+'</p><div class=\\'mfoot\\'>Move to another title to dismiss.</div></div></div>';return;}\n"
"  if(__screen==='queue'){m.innerHTML='<div class=\\'modalbg\\'><div class=\\'modalbox\\'>'+modalJobsHtml()+'</div></div>';return;}\n"
"  m.innerHTML='';\n"
"}\n"
"function scrollToSel(){var row=Math.floor(__sel/COLS);var top=(row===0)?0:(HDR+row*ROWH);var h=(row===0)?(HDR+CARDH):ROWH;try{__oopsy_scroll(top,h);}catch(e){}}\n"
"function render(){\n"
"  __screen='browse';\n"
"  __vis=visible();\n"
"  if(__sel>=__vis.length)__sel=__vis.length-1;if(__sel<0)__sel=0;\n"
"  renderChips();\n"
"  var body=__vis.length?gridHtml(__vis):'<p class=\\'empty\\'>No apps match this filter.</p>';\n"
"  var m=document.getElementById('main');if(m)m.innerHTML=body;\n"
"  DBG('render kind='+__kind+' status='+__status+' vis='+__vis.length+' sel='+__sel);\n"
"  scrollToSel();\n"
"}\n"
"function oopsyNav(dir){if(__screen!=='browse'){return;}if(__err){__err='';renderModal();}var n=__vis.length;if(!n)return;var s=__sel;\n"
"  if(dir==='left'){if(s>0)s--;}else if(dir==='right'){if(s<n-1)s++;}\n"
"  else if(dir==='up'){if(s-COLS>=0)s-=COLS;}else if(dir==='down'){if(s+COLS<n)s+=COLS;else if(s<n-1)s=n-1;}\n"
"  if(s!==__sel){__sel=s;DBG('nav '+dir+' sel='+s);render();}\n"
"}\n"
"function cycleKind(d){if(__err){__err='';renderModal();}var i=__kindKeys.indexOf(__kind);if(i<0)i=0;i=(i+d+__kindKeys.length)%__kindKeys.length;__kind=__kindKeys[i];__sel=0;render();}\n"
"function cycleStatus(d){if(__err){__err='';renderModal();}var i=__statusKeys.indexOf(__status);if(i<0)i=0;i=(i+d+__statusKeys.length)%__statusKeys.length;__status=__statusKeys[i];__sel=0;render();}\n"
"function oopsyEnter(){if(!__vis.length)return false;var a=__vis[__sel];\n"
"  if(!a.installable){oopsyError('No build available yet for '+(a.title||a.name)+' - nothing to download.');return false;}\n"
"  var ok=false;try{ok=!!__oopsy_install(a.name);}catch(e){DBG('install threw:'+e);ok=false;}\n"
"  DBG('enter install '+a.name+' ok='+ok);\n"
"  if(ok){a.queued=true;__err='';}\n"
"  return ok;\n"
"}\n"
"function oopsyScreen(name){DBG('screen '+name);__screen=(name==='queue')?'queue':'browse';\n"
"  document.getElementById('hint').innerHTML=(__screen==='queue')?'O back to apps':'D-pad move | X install | L1/R1 kind | L2/R2 readiness | [ ] downloads | O exit';\n"
"  if(__screen==='queue'){renderModal();}else{__err='';renderModal();render();}\n"
"}\n"
"function oopsyRefresh(){if(__screen!=='queue')return;renderModal();}\n"
"function oopsyError(msg){__err=msg||'';renderModal();}\n"
"function oLayoutDump(){try{var G=document.getElementById('main');var C=document.getElementById('card-0');function R(e){if(!e||!e.getBoundingClientRect)return 'na';var r=e.getBoundingClientRect();return r.x+','+r.y+' '+r.width+'x'+r.height;}DBG('LAYOUT main='+R(G)+' card0='+R(C)+' body='+R(document.body));}catch(e){DBG('LAYOUT threw:'+e);}}\n"
"function oopsyInit(){\n"
"  DBG('oopsyInit metafn='+(typeof __oopsy_meta)+' catfn='+(typeof __oopsy_catalog));\n"
"  try{__apps=buildApps();__sel=0;__screen='browse';render();DBG('oopsyInit apps='+__apps.length);}catch(e){DBG('oopsyInit THREW:'+e+' '+(e&&e.stack));}\n"
"}\n"
"window.oopsyNav=oopsyNav;window.oopsyCycleKind=cycleKind;window.oopsyCycleStatus=cycleStatus;\n"
"window.oopsyEnter=oopsyEnter;window.oopsyScreen=oopsyScreen;window.oopsyRefresh=oopsyRefresh;\n"
"window.oopsyError=oopsyError;window.oopsyInit=oopsyInit;window.oLayoutDump=oLayoutDump;\n"
"oopsyInit();\n"
"</script>\n"
"</body></html>\n";
