# NetSurf's source lists, read from its own make fragments rather than transcribed.
#
#   make -s -C <netsurf> -f <this file> print
#
# prints one source per line, relative to the NetSurf tree. It sets the switches the top-level
# Makefile would (`Makefile.defaults`, `frontends/framebuffer/Makefile.defaults`) to this port's
# choices, includes the same fragments in the same order, and composes `SOURCES` the way
# `frontends/framebuffer/Makefile:189` does - less `S_IMAGES` and `S_FONTS`, which are C files
# the build generates from `res/` and which `../Makefile` adds itself.
#
# The choices:
#   - cURL fetches; the `file:`, `data:`, `about:` and `resource:` fetchers are NetSurf's own.
#   - No JavaScript. Duktape's bindings are generated by `nsgenbind`, a flex and bison program,
#     and the build container has neither; `javascript/none` is upstream's own no-script build.
#   - BMP, GIF, PNG and JPEG images, through the bundle's decoders and oops-deps' libpng and
#     libjpeg-turbo. No SVG yet: libsvgtiny parses through libdom's XML binding, which needs
#     expat or libxml2, and neither is vendored. No WebP, JPEG XL, video or PDF.
#   - The internal bitmap font, so no font files ship; `NETSURF_FB_FONTLIB := internal`.
#   - No on-disk cache (`NETSURF_FS_BACKING_STORE := NO`, upstream's default).

TARGET := framebuffer
NETSURF_USE_CURL := YES
NETSURF_USE_DUKTAPE := NO
NETSURF_USE_BMP := YES
NETSURF_USE_GIF := YES
NETSURF_USE_PNG := YES
NETSURF_USE_JPEG := YES
NETSURF_USE_JPEGXL := NO
NETSURF_USE_NSSVG := NO
NETSURF_USE_RSVG := NO
NETSURF_USE_WEBP := NO
NETSURF_USE_VIDEO := NO
NETSURF_USE_ROSPRITE := NO
NETSURF_USE_HARU_PDF := NO
NETSURF_FS_BACKING_STORE := NO
NETSURF_FB_FONTLIB := internal

include content/Makefile
include utils/Makefile
include utils/http/Makefile
include utils/nsurl/Makefile
include desktop/Makefile

S_COMMON := $(S_CONTENT) $(S_FETCHERS) $(S_UTILS) $(S_HTTP) $(S_NSURL) $(S_DESKTOP) \
            $(S_JAVASCRIPT_BINDING)

# The framebuffer front end's own list, `frontends/framebuffer/Makefile:175-184`, repeated here:
# that file also runs `pkg-config` and defines the image and font conversion rules, none of
# which a source list needs.
S_FRONTEND := gui.c framebuffer.c schedule.c bitmap.c fetch.c findfile.c corewindow.c \
              local_history.c clipboard.c
S_FRONTEND += font_$(NETSURF_FB_FONTLIB).c
S_FRONTEND += $(addprefix fbtk/,fbtk.c event.c fill.c bitmap.c user.c window.c text.c \
                                scroll.c osk.c)
S_FRONTEND := $(addprefix frontends/framebuffer/,$(S_FRONTEND))

.PHONY: print
print:
	@for s in $(sort $(S_COMMON) $(S_IMAGE) $(S_BROWSER) $(S_FRONTEND)); do echo "$$s"; done
