#!/usr/bin/env python3
"""Generate `src/rune_table.c`, the C locale's character table that libc++ reads.

    python3 tools/gen-rune-table.py > src/rune_table.c

# Why this is generated

`std::ctype<char>::classic_table()` returns `_DefaultRuneLocale.__runetype` on this target, and
`std::ctype<char>::is()` then tests bits in it. Those answers must agree with `isalpha()` and its
kin from oops-sdk's `<libc/ctype.h>`, because a program that asks the same question two ways and
gets two answers is the worst kind of bug to find - it needs no invalid input and reproduces only
where the two paths are mixed.

The classifications in `classify()` are transcribed from those inline functions, once, here. A
hand-written 256-entry table would be a second transcription with no way to check it.

Re-run this after any change to oops-sdk's `<libc/ctype.h>` and commit the result; the output is
committed because a build must not depend on a Python interpreter.
"""

import sys

# Mask values, from oops-sdk's `include/libc/ctype.h`, which cites FreeBSD's `_ctype.h` for them.
A, C, D, L, P, S, U, X, B, R = (0x100, 0x200, 0x400, 0x1000, 0x2000,
                                0x4000, 0x8000, 0x10000, 0x20000, 0x40000)


def classify(c: int) -> int:
    """The mask for one byte. Mirrors `<libc/ctype.h>`'s inline predicates exactly."""
    lower = ord('a') <= c <= ord('z')
    upper = ord('A') <= c <= ord('Z')
    digit = ord('0') <= c <= ord('9')
    alpha = lower or upper
    alnum = alpha or digit
    space = c in (0x20, 0x09, 0x0a, 0x0b, 0x0c, 0x0d)
    blank = c in (0x20, 0x09)
    printable = 0x20 <= c < 0x7f
    graph = 0x20 < c < 0x7f
    cntrl = (0 <= c < 0x20) or c == 0x7f
    punct = graph and not alnum
    xdigit = digit or (ord('a') <= c <= ord('f')) or (ord('A') <= c <= ord('F'))

    m = 0
    for flag, bit in ((alpha, A), (cntrl, C), (digit, D), (lower, L), (punct, P),
                      (space, S), (upper, U), (xdigit, X), (blank, B), (printable, R)):
        if flag:
            m |= bit

    # runetype.h: "The lower 8 bits of runetype[] contain the digit value of the rune."
    # Harmless to the masks above, which all start at 0x100, and it is what the layout says.
    if digit:
        m |= c - ord('0')
    elif ord('a') <= c <= ord('f'):
        m |= c - ord('a') + 10
    elif ord('A') <= c <= ord('F'):
        m |= c - ord('A') + 10
    return m


def block(values, fmt, per_row):
    return "\n".join("        " + " ".join(fmt % v for v in values[i:i + per_row])
                     for i in range(0, 256, per_row))



HEADER = '''/* The C locale's character table, which libc++ reads as `_DefaultRuneLocale`.
 *
 * **GENERATED by `tools/gen-rune-table.py`. Do not edit by hand** - regenerate it, so that the
 * table and oops-sdk's `<libc/ctype.h>` cannot drift apart.
 *
 * Why this exists, why it lives here rather than in oops-sdk, and where the layout is
 * transcribed from are all in `include/runetype.h`, which declares the type this defines.
 */
#include <runetype.h>

const _RuneLocale _DefaultRuneLocale = {
    /* `_RUNE_MAGIC_1`, which is exactly 8 characters into a `char[8]`. Spelled out rather than
       written as "RuneMagi" because C drops the terminator for an exact fit and C++ rejects it,
       and this file is compiled as C++. */
    {'R', 'u', 'n', 'e', 'M', 'a', 'g', 'i'},
    "NONE",
    NULL,
    NULL,
    0xFFFD,

    /* __runetype: the class mask per byte. */
    {
'''

TAIL = '''    },
    {0, NULL},
    {0, NULL},
    {0, NULL},
    NULL,
    0,
};

/* `_CurrentRuneLocale` is the locale in force. There is one locale, so it is the default one and
   cannot become anything else. */
const _RuneLocale *_CurrentRuneLocale = &_DefaultRuneLocale;
'''


def main():
    types = [classify(c) for c in range(256)]
    lower = [c + 32 if ord('A') <= c <= ord('Z') else c for c in range(256)]
    upper = [c - 32 if ord('a') <= c <= ord('z') else c for c in range(256)]

    out = sys.stdout
    out.write(HEADER)
    out.write(block(types, "0x%08lXUL,", 6))
    out.write("\n    },\n\n    /* __maplower: tolower() per byte. */\n    {\n")
    out.write(block(lower, "0x%04X,", 12))
    out.write("\n    },\n\n    /* __mapupper: toupper() per byte. */\n    {\n")
    out.write(block(upper, "0x%04X,", 12))
    out.write("\n")
    out.write(TAIL)


if __name__ == "__main__":
    main()
