#!/usr/bin/env python3
"""Generate `shim/gl_loader_table.cpp`, the name-to-address table dEQP's loader reads.

    python3 tools/gen-gl-loader.py <libglapi_bridge.a> > shim/gl_loader_table.cpp

# Why a table at all

dEQP fills its `glw::Functions` through a `glw::FunctionLoader`, which is `get(name)` - the
shape of `eglGetProcAddress` or `dlsym`. This platform has neither: a title is statically linked
and there is no runtime symbol table to ask (`oops-apps` has a memory of that costing a session).
Mesa does not export `_glapi_get_proc_address` in this build either - checked across every
archive.

So the lookup has to exist at link time, and that is a table.

# Why it is generated from two sources and intersected

**The names come from upstream**, out of `glwInitGL33.inl` and `glwInitExtGL.inl` - every
function the GL 3.3 core loader and the extension loader will ask for. Taking them from the
generated files rather than from a list here means a CTS bump changes the set automatically.

**The addresses come from the link**, out of `nm` on Mesa's `libglapi_bridge.a`. Names that
archive defines get the real entry point; the rest get a stub that names itself and throws
`tcu::NotSupportedError`.

That intersection is the point, and **the refusal has to be a call that fails cleanly rather
than a null**. This file used to return `nullptr` for a name the driver does not have, on the
reasoning that "dEQP is written to handle a null - `glu::ContextInfo` checks before use". That
was never checked and it is false: on 2026-09-25 `KHR-GL46.info.vendor` created a 4.6 context,
presented a frame, then called a null slot and took the console's whole payload chain down with
`rip: 0000000000000000`. `KHR-GL30` had been safe only because the entry points it needs are all
present.

A stub that throws `NotSupportedError` is what the suite actually knows how to read: the case is
recorded NotSupported with the entry point named, and the run continues. It cannot fault, which
a null can and did.

# Why the declarations use upstream's own typedefs

Each entry needs the symbol's address, which needs a declaration. `glwFunctionTypes.inl` already
defines `glDrawArraysFunc` and its 800-odd siblings, so this declares `extern "C"
glw::glDrawArraysFunc glDrawArrays;` - exactly the right type, taken from the same generated
header the rest of the wrapper uses. Declaring them as `void f(void)` and casting would have
compiled too, and would have been a second, guessed copy of 856 signatures.
"""

import re
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent.parent
WRAPPER = HERE / "upstream" / "framework" / "opengl" / "wrapper"
INLS = ["glwInitGL33.inl", "glwInitExtGL.inl"]


def wanted_names():
    """Every (name, type) the GL 3.3 core and extension loaders ask for, in upstream's order.

    The *type* has to come out of the `.inl` beside the name rather than be derived from it.
    Most entries are `(glDrawArraysFunc) loader->get("glDrawArrays")`, where the typedef is the
    name plus `Func` - but an extension alias is not: `glDrawArraysInstancedARB` is cast to
    `glDrawArraysInstancedFunc`, because ARB and core share one signature and upstream declares
    it once. Assuming the name would invent `glDrawArraysInstancedARBFunc`, which does not exist,
    and the same goes for the whole `EXT`-suffixed indexed-state family.
    """
    out = []
    seen = set()
    pattern = re.compile(r'\((gl[A-Za-z0-9_]+Func)\)\s*loader->get\("(gl[A-Za-z0-9_]+)"\)')
    for inl in INLS:
        text = (WRAPPER / inl).read_text()
        for m in pattern.finditer(text):
            functype, name = m.group(1), m.group(2)
            if name not in seen:
                seen.add(name)
                out.append((name, functype))
    return out


def available_names(archive):
    """Every gl* symbol the archive defines, by nm."""
    out = subprocess.run(["llvm-nm", "--defined-only", archive],
                         capture_output=True, text=True, check=True).stdout
    return {m.group(1) for m in re.finditer(r"^\S+\s+[TtWwDd]\s+(gl[A-Za-z0-9_]+)$",
                                            out, re.MULTILINE)}


def main():
    if len(sys.argv) != 2:
        sys.exit("usage: gen-gl-loader.py <libglapi_bridge.a>")

    wanted = wanted_names()
    have = available_names(sys.argv[1])
    present = [(n, t) for (n, t) in wanted if n in have]
    missing = [n for (n, _) in wanted if n not in have]

    out = sys.stdout
    out.write('''/* The GL entry points dEQP's function loader can find.
 *
 * **GENERATED by `tools/gen-gl-loader.py`. Do not edit by hand.**
 *
 * Why this is a table rather than a `dlsym`, why the names come from upstream and the addresses
 * from the link, and why a missing entry is a null rather than an error, are all in that script.
 */
#include "glwDefs.hpp"
#include "glwFunctions.hpp"
#include "glwFunctionLoader.hpp"

/* `TCU_THROW(NotSupportedError, ...)` for the absent entry points below, and `oops_klog` so the
 * name reaches the system log even if something swallows the exception. */
#include "tcuDefs.hpp"
#include "oops/system.h"

#include <string.h>
#include <string>

namespace
{

struct Entry
{
    const char           *name;
    glw::GenericFuncType  func;
};

} // namespace

''')

    out.write('''/*
 * **`__typeof__(*(T)0)` and not plain `T`.** `glwFunctionTypes.inl`'s `glDrawArraysFunc` is a
 * *function pointer* typedef, so `extern glw::glDrawArraysFunc glDrawArrays;` declares a pointer
 * **variable** named `glDrawArrays` - not the function. The table below then compiles to a *read*
 * of that variable, and the symbol it resolves to is code.
 *
 * That builds, links and passes every check. On hardware it is a data read from the
 * execute-only text segment: `SYSTEM_XO_VIOLATION` inside this file's own initialiser, on the
 * first entry it touches, before dEQP prints a line.
 *
 * Dereferencing the pointer type once gives the function type, so these declare functions and
 * the casts below decay their addresses as intended.
 */
''')
    out.write("extern \"C\" {\n")
    for n, t in present:
        out.write(f"extern __typeof__(*(glw::{t})0) {n};\n")
    out.write("}\n\n")

    out.write(f'''/* ---------------------------------------------------------------- the absent ones

 * **An absent entry point is a named refusal, never a null.**
 *
 * This table used to return `nullptr` for the {len(missing)} of {len(wanted)} entry points Mesa's archive does
 * not define, on the stated grounds that "dEQP is written to handle a null - `glu::ContextInfo`
 * checks before use". That was asserted here and never checked, and it is false.
 *
 * `KHR-GL46.info.vendor` took the console down on 2026-09-25: a 4.6 context was created, a frame
 * was presented, and then the process called straight through a null table slot -
 *
 *     reason: page fault (user read instruction, page not present)
 *     fault address: 0000000000000000
 *     rip: 0000000000000000
 *
 * - which killed the payload chain and the machine with it. `KHR-GL30` had been safe only
 * because every entry point it happens to need is present; the null design was never safe, it
 * was untested.
 *
 * So every requested name now resolves to a real function. A name this build cannot serve gets a
 * stub that says which one it was and throws `tcu::NotSupportedError`, which is dEQP's own
 * vocabulary for "this build cannot do that": the case is recorded NotSupported, the run carries
 * on to the next one, and the log names the entry point. That is the answer the suite is built
 * to read, and it cannot fault.
 *
 * The stubs take no arguments and are cast to the caller's type. On SysV x86-64 a call with
 * arguments into a function that ignores them is harmless - the arguments sit in caller-saved
 * registers and any stack ones are the caller's to clean - and none of these ever returns
 * normally, so no return value is ever read.
 */
static void absent(const char *name)
{{
    oops_klog("OOPS-GL", name);
    TCU_THROW(NotSupportedError,
              (std::string("this build has no ") + name +
               " - it is not defined by the Mesa archive this title links")
                  .c_str());
}}

''')
    for n in missing:
        out.write(f'static void absent_{n}(void) {{ absent("{n}"); }}\n')
    out.write('static void absent_unknown(void) '
              '{ absent("an entry point this generator did not know about"); }\n\n')

    out.write("static const Entry s_entries[] = {\n")
    for n, _ in present:
        out.write(f'    {{"{n}", reinterpret_cast<glw::GenericFuncType>({n})}},\n')
    for n in missing:
        out.write(f'    {{"{n}", reinterpret_cast<glw::GenericFuncType>(absent_{n})}},\n')
    out.write("};\n\n")

    out.write(f'''/* Linear search over {len(present) + len(missing)} entries - {len(present)} real, {len(missing)} refusing. dEQP calls this once per
 * function at context creation and never again, so the whole cost is one pass at start-up; a
 * sorted table and a bisect would be faster to no purpose and would add an ordering nothing
 * checks. */
namespace oops
{{

/*
 * **Never returns null.** A name in the table resolves to the entry point or to its refusing
 * stub; a name that is not in the table at all - one upstream asks for that the generator did
 * not know about, which a CTS bump can produce - gets the same treatment rather than a null,
 * because the caller that crashed the console on 2026-09-25 did not check for one.
 */
glw::GenericFuncType glLoaderGet(const char *name)
{{
    for (unsigned i = 0; i < sizeof(s_entries) / sizeof(s_entries[0]); ++i)
        if (strcmp(s_entries[i].name, name) == 0)
            return s_entries[i].func;
    return reinterpret_cast<glw::GenericFuncType>(absent_unknown);
}}

unsigned glLoaderCount(void)
{{
    return sizeof(s_entries) / sizeof(s_entries[0]);
}}

}} // namespace oops
''')

    print(f"// {len(present)} of {len(wanted)} requested entry points are in this build.",
          file=sys.stderr)
    if missing:
        print(f"// absent: each gets a stub that names itself and throws NotSupportedError, so a "
              f"case that calls one is recorded NotSupported instead of faulting:",
              file=sys.stderr)
        for n in missing:
            print(f"//   {n}", file=sys.stderr)


if __name__ == "__main__":
    main()
