# sdl12-compat build integration: SDL 1.2's API over SDL2. Include from a title's Makefile,
# before `common/app.mk`:
#
#   OOPS_SDL12 ?= $(abspath ../../oops-deps/sdl12-compat)
#   include $(OOPS_SDL12)/oops-sdl12.mk
#
#   EXTRA_TARGET_CFLAGS  += $(OOPS_SDL12_INCLUDE)
#   EXTRA_TARGET_LDFLAGS += $(OOPS_SDL12_LDFLAGS)
#   PAYLOAD_EXTRA_DEPS   += $(OOPS_SDL12_LIB) $(OOPS_SDL12_SDL2_LIB)
#
# Do not also include `oops-sdl.mk` in the title: this file includes SDL2 itself and links a
# renamed copy of it. A title uses SDL 1.2 or SDL 2, not both.
#
# sdl12-compat is designed as a shared library that reaches SDL2 through `dlopen`; linked
# statically, its SDL 1.2 names collide with SDL2's. SDL2's archive is therefore renamed to
# `IGNORE_THIS_VERSION_OF_SDL_*`, the names upstream's `src/SDL20_include_wrapper.h` already
# declares SDL2's API under. The rename map is generated by `nm` from the built archive.

ifndef OOPS_SDL12_DIR
OOPS_SDL12_DIR := $(abspath $(dir $(lastword $(MAKEFILE_LIST))))
endif
OOPS_SDL12_UPSTREAM ?= $(OOPS_SDL12_DIR)/upstream
OOPS_SDL12_BUILD ?= $(OOPS_SDL12_DIR)/build

# The SDL2 underneath: its file list, config and backends. Its archive is copied here under
# the renamed symbols.
OOPS_SDL ?= $(abspath $(OOPS_SDL12_DIR)/../sdl2)
include $(OOPS_SDL)/oops-sdl.mk

OOPS_SDL12_INCLUDE := -I$(OOPS_SDL12_UPSTREAM)/include

OOPS_SDL12_LIB := $(OOPS_SDL12_BUILD)/libSDL12compat.a
OOPS_SDL12_SDL2_LIB := $(OOPS_SDL12_BUILD)/libSDL2-renamed.a

# Upstream code does not build under this repository's warning flags (see `oops-sdl.mk`).
# `SDL12_compat.c` includes SDL2's headers through its wrapper.
OOPS_SDL12_CFLAGS = $(filter-out $(OOPS_SDL_WARN_DROP),$(TARGET_CFLAGS)) -w \
                    $(OOPS_SDL_INCLUDE) $(OOPS_SDL12_INCLUDE)

# The renamed SDL2 archive is outside `--whole-archive`: sdl12-compat references the renamed
# names directly, so ordinary archive resolution pulls what is used.
OOPS_SDL12_LDFLAGS := -Wl,--whole-archive $(OOPS_SDL12_LIB) -Wl,--no-whole-archive \
                      $(OOPS_SDL12_SDL2_LIB)

$(OOPS_SDL12_SDL2_LIB): $(OOPS_SDL_LIB) $(lastword $(MAKEFILE_LIST))
	@mkdir -p $(OOPS_SDL12_BUILD)
	@nm_tool=$$(command -v $(NM) 2>/dev/null || command -v llvm-nm 2>/dev/null || command -v nm); \
	 oc_tool=$$(command -v $(OBJCOPY) 2>/dev/null || command -v llvm-objcopy 2>/dev/null || command -v objcopy); \
	 if [ -z "$$nm_tool" ] || [ -z "$$oc_tool" ]; then \
	   echo "oops-sdl12: need nm and objcopy to rename SDL2's symbols, and one is missing" >&2; \
	   exit 1; \
	 fi; \
	 "$$nm_tool" --defined-only -g $(OOPS_SDL_LIB) 2>/dev/null \
	   | awk '$$3 ~ /^SDL_/ { print $$3, "IGNORE_THIS_VERSION_OF_" $$3 }' | sort -u \
	   > $(OOPS_SDL12_BUILD)/rename.map; \
	 cp $(OOPS_SDL_LIB) $@; \
	 "$$oc_tool" --redefine-syms=$(OOPS_SDL12_BUILD)/rename.map $@; \
	 echo "oops-sdl12: renamed $$(wc -l < $(OOPS_SDL12_BUILD)/rename.map) SDL2 symbols"
	@echo "oops-sdl12: $@"

$(OOPS_SDL12_LIB): $(OOPS_SDL12_UPSTREAM)/src/SDL12_compat.c $(lastword $(MAKEFILE_LIST)) \
                   | $(OOPS_SDL12_SDL2_LIB)
	@mkdir -p $(OOPS_SDL12_BUILD)
	@rm -f $@
	$(TARGET_CC) $(OOPS_SDL12_CFLAGS) -c -o $(OOPS_SDL12_BUILD)/SDL12_compat.o \
	    $(OOPS_SDL12_UPSTREAM)/src/SDL12_compat.c
	@ar_tool=$$(command -v $(AR) 2>/dev/null || command -v llvm-ar 2>/dev/null || command -v ar); \
	 "$$ar_tool" rcs $@ $(OOPS_SDL12_BUILD)/SDL12_compat.o
	@echo "oops-sdl12: $@"

.PHONY: sdl12-clean sdl12-upstream sdl12-upstream-clean
sdl12-clean:
	@rm -rf $(OOPS_SDL12_BUILD)
	@echo "sdl12-compat: removed build/"

sdl12-upstream:
	@$(OOPS_SDL12_DIR)/../../../common/upstream-fetch.sh \
	    "$$(sed -n 's/^UPSTREAM_KIND=//p' $(OOPS_SDL12_DIR)/upstream.lock)" \
	    "$$(sed -n 's/^UPSTREAM_URL=//p'  $(OOPS_SDL12_DIR)/upstream.lock)" \
	    "$$(sed -n 's/^UPSTREAM_REV=//p'  $(OOPS_SDL12_DIR)/upstream.lock)" \
	    "$(OOPS_SDL12_UPSTREAM)" "$(OOPS_SDL12_DIR)/patches"

sdl12-upstream-clean:
	@rm -rf $(OOPS_SDL12_UPSTREAM)
	@echo "sdl12-compat: removed upstream/"
