#!/bin/sh
# Writes Luanti's `builtin_files.cpp`: the SHA-256 of each file under `builtin/`, which the
# engine compares a builtin Lua file against when it loads one and warns on a mismatch
# (`src/script/cpp_api/s_security.cpp`). Upstream's CMake does this at configure time
# (`cmake/Modules/HashBuiltinFiles.cmake`) over the list `builtin/CMakeLists.txt` names; this
# hashes every `.lua` there, a superset, so no builtin file the package carries goes unlisted.
#
#   gen-builtin-files.sh <luanti tree> <output .cpp>
#
# The output is rewritten only when it changes, so nothing recompiles for nothing.
set -eu
tree="$1"
out="$2"
mkdir -p "$(dirname "$out")"
{
    printf '// Generated by shim/gen-builtin-files.sh from builtin/.\n'
    printf '#include "builtin_files.h"\n\n'
    printf 'using namespace std::literals::string_view_literals;\n\n'
    printf 'const std::unordered_map<std::string_view, std::string_view> g_builtin_file_sha256_map = {\n'
    (cd "$tree/builtin" && find . -name '*.lua' | sort | while read -r f; do
        rel="${f#./}"
        hash="$(sha256sum "$f" | cut -d' ' -f1)"
        printf '\t{"%s"sv, "%s"sv},\n' "$rel" "$hash"
    done)
    printf '};\n'
} > "$out.tmp"
if cmp -s "$out.tmp" "$out" 2>/dev/null; then
    rm -f "$out.tmp"
else
    mv "$out.tmp" "$out"
fi
