/*
 * The platform layer: what dEQP needs to know about this console.
 *
 * `framework/platform/` holds one directory per operating system - X11, Win32, Android, OSX,
 * QNX, Fuchsia - and none of them is this one. This file is the equivalent, and it is
 * deliberately the *only* thing this port writes. Everything else compiled here is upstream's,
 * which is the property that makes a CTS result worth having.
 *
 * # What a platform owes dEQP, and nothing more
 *
 * Four things, and they are all in `gluRenderContext.hpp`:
 *
 *   - `getType()`        what GL version and profile this context is
 *   - `getFunctions()`   the `glw::Functions` table the tests call through
 *   - `getRenderTarget()` the size and format of what is being drawn to
 *   - `postIterate()`    present the frame; called at the end of each test case
 *
 * There is no event loop, no window manager, no surface negotiation. `oops_gl_create` opens the
 * display and makes a context current in one call, which is the whole of what the X11 platform
 * spends four files doing.
 *
 * # Only the GL platform is implemented
 *
 * `tcu::Platform` also offers `getEGLPlatform()` and `getVulkanPlatform()`, and the base class
 * implementations throw `NotSupportedError`. That is the correct answer here and it is left
 * alone: this collection has no EGL (oops-mesa D010 records why the DRI frontend is used
 * instead) and no Vulkan. A suite run asks for the GL platform and never reaches the others.
 */
#include "tcuPlatform.hpp"
#include "tcuRenderTarget.hpp"
#include "tcuCommandLine.hpp"

#include "gluPlatform.hpp"
#include "gluRenderContext.hpp"
#include "gluContextFactory.hpp"
#include "gluRenderConfig.hpp"

#include "glwFunctions.hpp"
#include "glwFunctionLoader.hpp"

extern "C" {
#include "oops/gfx.h"
#include "oops/system.h"
}

namespace oops
{

/* Defined in the generated `gl_loader_table.cpp`. */
glw::GenericFuncType glLoaderGet(const char *name);
unsigned             glLoaderCount(void);

namespace
{

/*
 * The loader, which is a table lookup rather than a symbol lookup.
 *
 * A title here is statically linked and has no runtime symbol table to ask - `dlsym` does not
 * exist and Mesa does not export `_glapi_get_proc_address` in this build, both checked. So the
 * lookup happens at link time, in a table generated by `tools/gen-gl-loader.py` from upstream's
 * own `glwInitGL33.inl` intersected with what Mesa's `libglapi_bridge.a` actually defines.
 *
 * **A null return is a real answer, not a failure.** dEQP is written for it: `glu::ContextInfo`
 * checks a function pointer before using it and a test whose entry point is absent reports
 * `NotSupported`. Returning a plausible pointer for something the driver does not have would
 * turn that into a fault inside the test.
 */
class FunctionLoader : public glw::FunctionLoader
{
public:
    glw::GenericFuncType get(const char *name) const override
    {
        return glLoaderGet(name);
    }
};

class RenderContext : public glu::RenderContext
{
public:
    RenderContext(const glu::RenderConfig &config);
    ~RenderContext(void) override;

    glu::ContextType getType(void) const override
    {
        return m_type;
    }
    const glw::Functions &getFunctions(void) const override
    {
        return m_functions;
    }
    const tcu::RenderTarget &getRenderTarget(void) const override
    {
        return m_renderTarget;
    }

    void postIterate(void) override;

private:
    glu::ContextType  m_type;
    struct oops_gfx  *m_gfx;
    glw::Functions    m_functions;
    tcu::RenderTarget m_renderTarget;
};

/*
 * The size is the display's, not the configuration's.
 *
 * `glu::RenderConfig` carries a width and height that the command line can set, and on a desktop
 * they become a window. Here there is one display at one size and no way to make a smaller one,
 * so a request for anything else cannot be honoured. `DONT_CARE` is what upstream uses for "the
 * platform decides", and this platform always decides - so the request is read for what it is
 * worth and then the real extent is reported through `getRenderTarget()`, which is what the
 * tests actually size themselves against.
 *
 * Saying so here matters because a test that asked for 256x256 and silently got 1920x1080 would
 * produce a correct-looking result about the wrong surface.
 */
RenderContext::RenderContext(const glu::RenderConfig &config)
    : m_type(config.type)
    , m_gfx(nullptr)
    , m_renderTarget(0, 0, tcu::PixelFormat(0, 0, 0, 0), 0, 0, 0)
{
    /*
     * The requested width and height are passed through rather than ignored - `oops_gfx_create`
     * takes 0 for "the display's own", and a test that asked for a specific size gets asked for.
     * What it actually got is read back below and reported, because the two can differ and the
     * tests must size themselves against the second.
     */
    const oops_gfx_desc_t desc = {
        static_cast<uint32_t>(config.width  > 0 ? config.width  : 0),
        static_cast<uint32_t>(config.height > 0 ? config.height : 0),
        true, /* depth: the CTS depth-buffer cases need one and it costs nothing here */
        true, /* vsync: a present that outruns scanout overran the flip queue (oops-mesa 071) */
    };

    m_gfx = oops_gfx_create(&desc);
    if (m_gfx == nullptr)
        TCU_FAIL("oops_gfx_create failed: no GL context");

    uint32_t width = 0, height = 0;
    oops_gfx_extent(m_gfx, &width, &height);

    /*
     * 8888 with a 24-bit depth buffer and 8 stencil is what `oops_gfx_create` opens, and it is
     * not configurable today. Reported rather than assumed by the tests: `tcu::RenderTarget` is
     * where dEQP reads the format it must compare against, and a wrong answer here makes every
     * image comparison wrong in a way that looks like a driver bug.
     */
    m_renderTarget = tcu::RenderTarget(static_cast<int>(width), static_cast<int>(height),
                                       tcu::PixelFormat(8, 8, 8, 8), 24, 8, 0);

    const FunctionLoader loader;
    glu::initCoreFunctions(&m_functions, &loader, m_type.getAPI());
    glu::initExtensionFunctions(&m_functions, &loader, m_type.getAPI());
}

RenderContext::~RenderContext(void)
{
    if (m_gfx != nullptr)
        oops_gfx_destroy(m_gfx);
}

/*
 * Called at the end of every test case. On a desktop this is the buffer swap, and it is also
 * where a windowing platform pumps its event queue - there is no queue here.
 *
 * Presenting between cases is not decoration: it is what makes a run watchable on the panel, and
 * a run nobody can watch is one where a hang looks the same as a slow test.
 */
void RenderContext::postIterate(void)
{
    if (m_gfx != nullptr)
        oops_gfx_present(m_gfx);
}

class ContextFactory : public glu::ContextFactory
{
public:
    ContextFactory(void)
        : glu::ContextFactory("oops", "OpenGL context through oops-mesa on the console display")
    {
    }

    glu::RenderContext *createContext(const glu::RenderConfig &config, const tcu::CommandLine &,
                                      const glu::RenderContext *) const override
    {
        return new RenderContext(config);
    }
};

class GLPlatform : public glu::Platform
{
public:
    GLPlatform(void)
    {
        m_contextFactoryRegistry.registerFactory(new ContextFactory());
    }
};

class Platform : public tcu::Platform
{
public:
    const glu::Platform &getGLPlatform(void) const override
    {
        return m_glPlatform;
    }

private:
    GLPlatform m_glPlatform;
};

} // namespace
} // namespace oops

/*
 * dEQP's entry point into the platform, declared by `tcuMain.cpp` and by every platform
 * directory upstream ships.
 */
tcu::Platform *createPlatform(void)
{
    return new oops::Platform();
}

/*
 * A C-callable way into `tcuMain.cpp`'s `main`, because under `-ffreestanding` it is not `main`.
 *
 * C++ special-cases `int main(int, char **)` at namespace scope: it is the program's entry
 * point, it gets C linkage without being asked, and it may not be called. **`-ffreestanding`
 * withdraws that**, because a freestanding program's entry point is whatever the link says it
 * is - so `main` becomes an ordinary function, mangles to `_Z4mainiPPc`, and is callable like
 * any other.
 *
 * `common/cxx.mk` compiles with `-ffreestanding`, so upstream's `main` is in the archive under
 * the mangled name. `shim/gl_cts_entry.c` is C and cannot spell that, and declaring
 * `extern "C" int main(...)` here would not match either. This wrapper is compiled as C++,
 * beside the same rule, so it names the symbol the way the compiler wrote it.
 *
 * The symptom of getting this wrong is not a link error: a payload links
 * `--unresolved-symbols=ignore-all`, so `main` stayed undefined through several builds and only
 * the import manifest - which refuses to write one for a name it cannot place - said so.
 */
int main(int argc, char **argv); /* upstream's, in tcuMain.cpp */

extern "C" int oops_cts_run_main(int argc, char **argv)
{
    return main(argc, argv);
}
