#!/usr/bin/env python3
"""Generate `shim/gl_loader_table.cpp`, the name-to-address table dEQP's loader reads.

    python3 tools/gen-gl-loader.py <libglapi_bridge.a> > shim/gl_loader_table.cpp

# Why a table at all

dEQP fills its `glw::Functions` through a `glw::FunctionLoader`, which is `get(name)` - the
shape of `eglGetProcAddress` or `dlsym`. This platform has neither: a title is statically linked
and there is no runtime symbol table to ask (`oops-apps` has a memory of that costing a session).
Mesa does not export `_glapi_get_proc_address` in this build either - checked across every
archive.

So the lookup has to exist at link time, and that is a table.

# Why it is generated from two sources and intersected

**The names come from upstream**, out of `glwInitGL33.inl` and `glwInitExtGL.inl` - every
function the GL 3.3 core loader and the extension loader will ask for. Taking them from the
generated files rather than from a list here means a CTS bump changes the set automatically.

**The addresses come from the link**, out of `nm` on Mesa's `libglapi_bridge.a`. Only names that
archive actually defines get an entry; everything else is absent from the table and `get()`
returns null for it.

That intersection is the point. A loader that returned a plausible pointer for a function the
driver does not have would produce a test that calls it and faults, and dEQP is written to
handle a null - `glu::ContextInfo` checks before use, and a test whose entry point is missing
reports `NotSupported` rather than crashing. **Null is the honest answer and the suite knows
what to do with it.**

# Why the declarations use upstream's own typedefs

Each entry needs the symbol's address, which needs a declaration. `glwFunctionTypes.inl` already
defines `glDrawArraysFunc` and its 800-odd siblings, so this declares `extern "C"
glw::glDrawArraysFunc glDrawArrays;` - exactly the right type, taken from the same generated
header the rest of the wrapper uses. Declaring them as `void f(void)` and casting would have
compiled too, and would have been a second, guessed copy of 856 signatures.
"""

import re
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent.parent
WRAPPER = HERE / "upstream" / "framework" / "opengl" / "wrapper"
INLS = ["glwInitGL33.inl", "glwInitExtGL.inl"]


def wanted_names():
    """Every (name, type) the GL 3.3 core and extension loaders ask for, in upstream's order.

    The *type* has to come out of the `.inl` beside the name rather than be derived from it.
    Most entries are `(glDrawArraysFunc) loader->get("glDrawArrays")`, where the typedef is the
    name plus `Func` - but an extension alias is not: `glDrawArraysInstancedARB` is cast to
    `glDrawArraysInstancedFunc`, because ARB and core share one signature and upstream declares
    it once. Assuming the name would invent `glDrawArraysInstancedARBFunc`, which does not exist,
    and the same goes for the whole `EXT`-suffixed indexed-state family.
    """
    out = []
    seen = set()
    pattern = re.compile(r'\((gl[A-Za-z0-9_]+Func)\)\s*loader->get\("(gl[A-Za-z0-9_]+)"\)')
    for inl in INLS:
        text = (WRAPPER / inl).read_text()
        for m in pattern.finditer(text):
            functype, name = m.group(1), m.group(2)
            if name not in seen:
                seen.add(name)
                out.append((name, functype))
    return out


def available_names(archive):
    """Every gl* symbol the archive defines, by nm."""
    out = subprocess.run(["llvm-nm", "--defined-only", archive],
                         capture_output=True, text=True, check=True).stdout
    return {m.group(1) for m in re.finditer(r"^\S+\s+[TtWwDd]\s+(gl[A-Za-z0-9_]+)$",
                                            out, re.MULTILINE)}


def main():
    if len(sys.argv) != 2:
        sys.exit("usage: gen-gl-loader.py <libglapi_bridge.a>")

    wanted = wanted_names()
    have = available_names(sys.argv[1])
    present = [(n, t) for (n, t) in wanted if n in have]
    missing = [n for (n, _) in wanted if n not in have]

    out = sys.stdout
    out.write('''/* The GL entry points dEQP's function loader can find.
 *
 * **GENERATED by `tools/gen-gl-loader.py`. Do not edit by hand.**
 *
 * Why this is a table rather than a `dlsym`, why the names come from upstream and the addresses
 * from the link, and why a missing entry is a null rather than an error, are all in that script.
 */
#include "glwDefs.hpp"
#include "glwFunctions.hpp"
#include "glwFunctionLoader.hpp"

#include <string.h>

namespace
{

struct Entry
{
    const char           *name;
    glw::GenericFuncType  func;
};

} // namespace

''')

    out.write('''/*
 * **`__typeof__(*(T)0)` and not plain `T`.** `glwFunctionTypes.inl`'s `glDrawArraysFunc` is a
 * *function pointer* typedef, so `extern glw::glDrawArraysFunc glDrawArrays;` declares a pointer
 * **variable** named `glDrawArrays` - not the function. The table below then compiles to a *read*
 * of that variable, and the symbol it resolves to is code.
 *
 * That builds, links and passes every check. On hardware it is a data read from the
 * execute-only text segment: `SYSTEM_XO_VIOLATION` inside this file's own initialiser, on the
 * first entry it touches, before dEQP prints a line.
 *
 * Dereferencing the pointer type once gives the function type, so these declare functions and
 * the casts below decay their addresses as intended.
 */
''')
    out.write("extern \"C\" {\n")
    for n, t in present:
        out.write(f"extern __typeof__(*(glw::{t})0) {n};\n")
    out.write("}\n\n")

    out.write("static const Entry s_entries[] = {\n")
    for n, _ in present:
        out.write(f'    {{"{n}", reinterpret_cast<glw::GenericFuncType>({n})}},\n')
    out.write("};\n\n")

    out.write(f'''/* Linear search over {len(present)} entries. dEQP calls this once per function at context
 * creation and never again, so the whole cost is one pass at start-up; a sorted table and a
 * bisect would be faster to no purpose and would add an ordering nothing checks. */
namespace oops
{{

glw::GenericFuncType glLoaderGet(const char *name)
{{
    for (unsigned i = 0; i < sizeof(s_entries) / sizeof(s_entries[0]); ++i)
        if (strcmp(s_entries[i].name, name) == 0)
            return s_entries[i].func;
    return nullptr;
}}

unsigned glLoaderCount(void)
{{
    return sizeof(s_entries) / sizeof(s_entries[0]);
}}

}} // namespace oops
''')

    print(f"// {len(present)} of {len(wanted)} requested entry points are in this build.",
          file=sys.stderr)
    if missing:
        print(f"// absent, so get() returns null and the suite reports NotSupported:",
              file=sys.stderr)
        for n in missing:
            print(f"//   {n}", file=sys.stderr)


if __name__ == "__main__":
    main()
