/*
 * gl-cube: Clean-room 3D Colored Cube Demo using oops-gl (OpenGL 1.3 / GLU)
 * Target: Sony PlayStation 5 (AMD RDNA2 GFX10.3 / Prospero FW 12.40)
 */

#include "GL/gl.h"
#include "GL/glu.h"
#include "oops/display.h"
#include "oops/draw.h"
#include "oops/input.h"
#include "oops/time.h"
#include "oops/memory.h"
#include "oops/syscall.h"
#include "oops/freestd.h"
#include "oops/krw.h"
#include "oops/fs.h"
#include "oops/system.h"
#include "obj_loader.h"
#include <stdbool.h>

typedef enum {
    GEOM_CUBE = 0,
    GEOM_TORUS = 1,
    GEOM_SPHERE = 2,
    GEOM_MAX
} geom_mode_t;

#ifndef OOPS_HOST_BUILD
/* A file pushed to the title directory ends the session cleanly - for a target driven over the
 * network, where no controller is at hand and no signal ends a process holding a GPU queue.
 * The name carries this run's process id, so a file left behind by an earlier run is ignored
 * and nothing has to be read or unlinked: existence is the whole signal. */
#define GL_CUBE_STOP_PREFIX "/app0/stop." /* the title directory as the sandbox mounts it; pushed to /data/homebrew/GLCB00001/stop.<pid> from outside */

/* The command-stream preamble Mesa's AMD driver would emit for this hardware, generated by
 * oops-mesa (tools/preamble-dump) from the pinned Mesa and included when that sibling checkout
 * is present; the control files preamble-a and preamble-b put it in front of every frame. */
#if !defined(OOPS_HOST_BUILD) && defined(__has_include)
#  if __has_include("preamble_gfx1013.h")
#    include "preamble_gfx1013.h"
#    define GL_CUBE_HAVE_MESA_PREAMBLE 1
#  endif
#endif
#ifndef GL_CUBE_HAVE_MESA_PREAMBLE
#  define GL_CUBE_HAVE_MESA_PREAMBLE 0
#endif

static int cube_stop_file_present(const char *path) {
    return oops_fs_exists(path) ? 1 : 0;
}

static void cube_klog(const char *msg) {
    oops_klog("GL-CUBE", msg);
}
#endif

/* 36 vertices defining 12 triangles of a 3D unit cube centered at origin */
static const GLfloat s_cube_vertices[36 * 3] = {
    /* Front Face (Z = +1.0) */
    -1.0f, -1.0f,  1.0f,
     1.0f, -1.0f,  1.0f,
     1.0f,  1.0f,  1.0f,
    -1.0f, -1.0f,  1.0f,
     1.0f,  1.0f,  1.0f,
    -1.0f,  1.0f,  1.0f,

    /* Back Face (Z = -1.0) */
     1.0f, -1.0f, -1.0f,
    -1.0f, -1.0f, -1.0f,
    -1.0f,  1.0f, -1.0f,
     1.0f, -1.0f, -1.0f,
    -1.0f,  1.0f, -1.0f,
     1.0f,  1.0f, -1.0f,

    /* Top Face (Y = +1.0) */
    -1.0f,  1.0f,  1.0f,
     1.0f,  1.0f,  1.0f,
     1.0f,  1.0f, -1.0f,
    -1.0f,  1.0f,  1.0f,
     1.0f,  1.0f, -1.0f,
    -1.0f,  1.0f, -1.0f,

    /* Bottom Face (Y = -1.0) */
    -1.0f, -1.0f, -1.0f,
     1.0f, -1.0f, -1.0f,
     1.0f, -1.0f,  1.0f,
    -1.0f, -1.0f, -1.0f,
     1.0f, -1.0f,  1.0f,
    -1.0f, -1.0f,  1.0f,

    /* Right Face (X = +1.0) */
     1.0f, -1.0f,  1.0f,
     1.0f, -1.0f, -1.0f,
     1.0f,  1.0f, -1.0f,
     1.0f, -1.0f,  1.0f,
     1.0f,  1.0f, -1.0f,
     1.0f,  1.0f,  1.0f,

    /* Left Face (X = -1.0) */
    -1.0f, -1.0f, -1.0f,
    -1.0f, -1.0f,  1.0f,
    -1.0f,  1.0f,  1.0f,
    -1.0f, -1.0f, -1.0f,
    -1.0f,  1.0f,  1.0f,
    -1.0f,  1.0f, -1.0f
};

/* Vivid per-vertex colors for hardware Gouraud shading */
static const GLfloat s_cube_colors[36 * 3] = {
    /* Front Face (Z = +1.0) */
    0.15f, 0.15f, 1.00f,
    1.00f, 0.15f, 1.00f,
    1.00f, 1.00f, 1.00f,
    0.15f, 0.15f, 1.00f,
    1.00f, 1.00f, 1.00f,
    0.15f, 1.00f, 1.00f,

    /* Back Face (Z = -1.0) */
    0.15f, 0.15f, 0.15f,
    0.15f, 1.00f, 0.15f,
    1.00f, 1.00f, 0.15f,
    0.15f, 0.15f, 0.15f,
    1.00f, 1.00f, 0.15f,
    1.00f, 0.15f, 0.15f,

    /* Top Face (Y = +1.0) */
    0.15f, 1.00f, 0.15f,
    0.15f, 1.00f, 1.00f,
    1.00f, 1.00f, 1.00f,
    0.15f, 1.00f, 0.15f,
    1.00f, 1.00f, 1.00f,
    1.00f, 1.00f, 0.15f,

    /* Bottom Face (Y = -1.0) */
    0.15f, 0.15f, 0.15f,
    1.00f, 0.15f, 0.15f,
    1.00f, 0.15f, 1.00f,
    0.15f, 0.15f, 0.15f,
    1.00f, 0.15f, 1.00f,
    0.15f, 0.15f, 1.00f,

    /* Right Face (X = +1.0) */
    1.00f, 0.15f, 1.00f,
    1.00f, 0.15f, 0.15f,
    1.00f, 1.00f, 0.15f,
    1.00f, 0.15f, 1.00f,
    1.00f, 1.00f, 0.15f,
    1.00f, 1.00f, 1.00f,

    /* Left Face (X = -1.0) */
    0.15f, 0.15f, 0.15f,
    0.15f, 0.15f, 1.00f,
    0.15f, 1.00f, 1.00f,
    0.15f, 0.15f, 0.15f,
    0.15f, 1.00f, 1.00f,
    0.15f, 1.00f, 0.15f
};

/* UV texture coordinates for 36 vertices (6 faces * 2 triangles * 3 vertices) */
static const GLfloat s_cube_texcoords[36 * 2] = {
    /* Front Face */
    0.0f, 0.0f,  1.0f, 0.0f,  1.0f, 1.0f,
    0.0f, 0.0f,  1.0f, 1.0f,  0.0f, 1.0f,

    /* Back Face */
    0.0f, 0.0f,  1.0f, 0.0f,  1.0f, 1.0f,
    0.0f, 0.0f,  1.0f, 1.0f,  0.0f, 1.0f,

    /* Top Face */
    0.0f, 0.0f,  1.0f, 0.0f,  1.0f, 1.0f,
    0.0f, 0.0f,  1.0f, 1.0f,  0.0f, 1.0f,

    /* Bottom Face */
    0.0f, 0.0f,  1.0f, 0.0f,  1.0f, 1.0f,
    0.0f, 0.0f,  1.0f, 1.0f,  0.0f, 1.0f,

    /* Right Face */
    0.0f, 0.0f,  1.0f, 0.0f,  1.0f, 1.0f,
    0.0f, 0.0f,  1.0f, 1.0f,  0.0f, 1.0f,

    /* Left Face */
    0.0f, 0.0f,  1.0f, 0.0f,  1.0f, 1.0f,
    0.0f, 0.0f,  1.0f, 1.0f,  0.0f, 1.0f
};

/* 36 surface normal vectors for 6 cube faces */
static const GLfloat s_cube_normals[36 * 3] = {
    /* Front Face (Z = +1.0) */
     0.0f,  0.0f,  1.0f,   0.0f,  0.0f,  1.0f,   0.0f,  0.0f,  1.0f,
     0.0f,  0.0f,  1.0f,   0.0f,  0.0f,  1.0f,   0.0f,  0.0f,  1.0f,

    /* Back Face (Z = -1.0) */
     0.0f,  0.0f, -1.0f,   0.0f,  0.0f, -1.0f,   0.0f,  0.0f, -1.0f,
     0.0f,  0.0f, -1.0f,   0.0f,  0.0f, -1.0f,   0.0f,  0.0f, -1.0f,

    /* Top Face (Y = +1.0) */
     0.0f,  1.0f,  0.0f,   0.0f,  1.0f,  0.0f,   0.0f,  1.0f,  0.0f,
     0.0f,  1.0f,  0.0f,   0.0f,  1.0f,  0.0f,   0.0f,  1.0f,  0.0f,

    /* Bottom Face (Y = -1.0) */
     0.0f, -1.0f,  0.0f,   0.0f, -1.0f,  0.0f,   0.0f, -1.0f,  0.0f,
     0.0f, -1.0f,  0.0f,   0.0f, -1.0f,  0.0f,   0.0f, -1.0f,  0.0f,

    /* Right Face (X = +1.0) */
     1.0f,  0.0f,  0.0f,   1.0f,  0.0f,  0.0f,   1.0f,  0.0f,  0.0f,
     1.0f,  0.0f,  0.0f,   1.0f,  0.0f,  0.0f,   1.0f,  0.0f,  0.0f,

    /* Left Face (X = -1.0) */
    -1.0f,  0.0f,  0.0f,  -1.0f,  0.0f,  0.0f,  -1.0f,  0.0f,  0.0f,
    -1.0f,  0.0f,  0.0f,  -1.0f,  0.0f,  0.0f,  -1.0f,  0.0f,  0.0f
};

#define TEX_DIM 64
static uint32_t s_cube_texture[TEX_DIM * TEX_DIM];

static void generate_cube_texture(void) {
    for (int y = 0; y < TEX_DIM; y++) {
        for (int x = 0; x < TEX_DIM; x++) {
            int cx = (x / 8) & 1;
            int cy = (y / 8) & 1;
            bool tile = (cx ^ cy) != 0;
            bool border = (x % 8 == 0) || (y % 8 == 0);

            uint8_t r, g, b, a = 255;
            if (border) {
                r = 255; g = 215; b = 0;   /* Gold grid lines */
            } else if (tile) {
                r = 240; g = 240; b = 255; /* Bright white-blue tile */
            } else {
                r = 30;  g = 60;  b = 140; /* Deep cobalt tile */
            }
            s_cube_texture[y * TEX_DIM + x] = ((uint32_t)a << 24) | ((uint32_t)b << 16) | ((uint32_t)g << 8) | (uint32_t)r;
        }
    }
}

static void int_to_str(int val, char *buf) {
    if (val == 0) {
        buf[0] = '0';
        buf[1] = '\0';
        return;
    }
    char tmp[16];
    int pos = 0;
    int v = val < 0 ? -val : val;
    while (v > 0) {
        tmp[pos++] = (char)('0' + (v % 10));
        v /= 10;
    }
    int out = 0;
    if (val < 0) buf[out++] = '-';
    for (int i = pos - 1; i >= 0; i--) {
        buf[out++] = tmp[i];
    }
    buf[out] = '\0';
}

static void hex_to_str(uint32_t val, char *buf) {
    buf[0] = '0'; buf[1] = 'x';
    for (int i = 7; i >= 0; i--) {
        uint8_t d = (uint8_t)(val & 0xf);
        buf[2 + i] = (char)(d < 10 ? ('0' + d) : ('a' + d - 10));
        val >>= 4;
    }
    buf[10] = '\0';
}

#ifndef OOPS_HOST_BUILD
static void cube_klog_hex(const char *tag, uint32_t v) {
    char msg[64];
    int n = 0;
    while (tag[n] && n < 40) { msg[n] = tag[n]; n++; }
    msg[n++] = ' ';
    hex_to_str(v, &msg[n]);
    cube_klog(msg);
}

/* The previous frame's pixels, kept only in paused runs so the frames either side of a state
 * toggle can be compared pixel for pixel. */
static uint32_t *s_prev_frame; /* allocated on first use, only in paused runs */
#endif

static int cube_append(char *dst, int at, const char *s) {
    while (*s && at < 126) dst[at++] = *s++;
    dst[at] = '\0';
    return at;
}

int gl_cube_start(const payload_args_t *args);

__attribute__((visibility("default"))) int gl_cube_start(const payload_args_t *args) {
#ifndef OOPS_HOST_BUILD
    if (args) {
        sys_call_init(args);
    }
    cube_klog("starting gl-cube (Stage 2 oops-gl 3D Cube demo)...");
    char stop_path[64];
    {
        char pid_str[16];
        int_to_str((int)sys_call(SYS_getpid, 0, 0, 0, 0, 0, 0), pid_str);
        int sp = 0;
        for (int i = 0; GL_CUBE_STOP_PREFIX[i]; i++) stop_path[sp++] = GL_CUBE_STOP_PREFIX[i];
        for (int i = 0; pid_str[i] && sp < (int)sizeof(stop_path) - 1; i++) stop_path[sp++] = pid_str[i];
        stop_path[sp] = '\0';
        cube_klog(stop_path);
    }
#endif

    /* 1. Open display via AGC backend */
    oops_display_t *disp = oops_display_open(OOPS_DISPLAY_BACKEND_AUTO, 1920, 1080);
    if (!disp || !oops_display_is_ready(disp)) {
#ifndef OOPS_HOST_BUILD
        cube_klog("failed to open display");
#endif
        return -1;
    }

    /* 2. Create OpenGL context */
    void *gl_ctx = glContextCreate(disp);
    if (!gl_ctx) {
#ifndef OOPS_HOST_BUILD
        cube_klog("failed to create oops-gl context");
#endif
        oops_display_close(disp);
        return -2;
    }
    glContextMakeCurrent(gl_ctx);

    /* 3. Configure OpenGL state machine */
    /* Configure initial OpenGL state */
    glViewport(0, 0, 1920, 1080);
    glDisable(GL_DEPTH_TEST);
    glDepthFunc(GL_LESS);
    glDepthMask(GL_TRUE);
    glEnable(GL_CULL_FACE);
    glCullFace(GL_BACK);
    glFrontFace(GL_CCW);
    glShadeModel(GL_SMOOTH);

    /* Generate and upload 2D procedural test texture */
    generate_cube_texture();
    GLuint tex_id = 0;
    glGenTextures(1, &tex_id);
    glBindTexture(GL_TEXTURE_2D, tex_id);
    glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_LINEAR);
    glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_LINEAR);
    glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_S, GL_REPEAT);
    glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_T, GL_REPEAT);
    glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA, TEX_DIM, TEX_DIM, 0, GL_RGBA, GL_UNSIGNED_BYTE, s_cube_texture);
#ifndef OOPS_HOST_BUILD
    cube_klog_hex("tex-image-error", (uint32_t)glGetError()); /* GL_OUT_OF_MEMORY would mean no GPU memory for the texture */
#endif
    glDisable(GL_TEXTURE_2D);

    /* 4. Configure Fixed-Function Lighting & Materials (Stage 6) */
    glEnable(GL_LIGHTING);
    glEnable(GL_LIGHT0);
    glEnable(GL_NORMALIZE);
    glEnable(GL_COLOR_MATERIAL);
    glColorMaterial(GL_FRONT_AND_BACK, GL_AMBIENT_AND_DIFFUSE);

    float light_pos[4] = {2.0f, 3.5f, 4.0f, 1.0f};
    float light_diff[4] = {1.0f, 0.96f, 0.90f, 1.0f};
    float light_amb[4] = {0.25f, 0.25f, 0.30f, 1.0f};
    float light_spec[4] = {1.0f, 1.0f, 1.0f, 1.0f};
    glLightfv(GL_LIGHT0, GL_POSITION, light_pos);
    glLightfv(GL_LIGHT0, GL_DIFFUSE, light_diff);
    glLightfv(GL_LIGHT0, GL_AMBIENT, light_amb);
    glLightfv(GL_LIGHT0, GL_SPECULAR, light_spec);

    float mat_spec[4] = {0.9f, 0.9f, 0.9f, 1.0f};
    glMaterialfv(GL_FRONT_AND_BACK, GL_SPECULAR, mat_spec);
    glMaterialf(GL_FRONT_AND_BACK, GL_SHININESS, 32.0f);

    /* Bind vertex, normal, color, and texture coordinate arrays */
    glEnableClientState(GL_VERTEX_ARRAY);
    glEnableClientState(GL_NORMAL_ARRAY);
    glEnableClientState(GL_COLOR_ARRAY);
    glEnableClientState(GL_TEXTURE_COORD_ARRAY);
    glVertexPointer(3, GL_FLOAT, 0, s_cube_vertices);
    glNormalPointer(GL_FLOAT, 0, s_cube_normals);
    glColorPointer(3, GL_FLOAT, 0, s_cube_colors);
    glTexCoordPointer(2, GL_FLOAT, 0, s_cube_texcoords);

    /* Initialize procedural meshes (Torus & Sphere) */
    oops_mesh_t torus_mesh;
    memset(&torus_mesh, 0, sizeof(torus_mesh));
    (void)oops_mesh_create_torus(&torus_mesh, 24, 16, 0.75f, 0.35f);

    oops_mesh_t sphere_mesh;
    memset(&sphere_mesh, 0, sizeof(sphere_mesh));
    (void)oops_mesh_create_sphere(&sphere_mesh, 20, 20, 0.95f);

    /* Initialize controller input */
    oops_input_init();

    geom_mode_t geom_mode = GEOM_CUBE;
    float rot_x = 25.0f;
    float rot_y = 35.0f;
    float rot_z = 10.0f;
    float cam_dist = -4.5f;
#ifndef OOPS_HOST_BUILD
    /* Control files pushed next to the stop file before launch fix the run's mode. */
    const bool ctl_pause = cube_stop_file_present("/app0/pause") != 0;     /* no animation: one fixed orientation */
    const bool ctl_dump = cube_stop_file_present("/app0/dump") != 0;       /* frame 30 logs the oracle record */
    const bool ctl_nodepth = cube_stop_file_present("/app0/nodepth") != 0; /* start with the depth test off */
    const bool ctl_tex = cube_stop_file_present("/app0/tex") != 0;         /* start with the texture on */
    /* oops-mesa unit 2: open every frame's stream with the preamble Mesa's AMD driver would emit,
     * variant A (with CLEAR_STATE) or B (without), and measure what the compositor makes of it. */
    const bool ctl_preamble_a = cube_stop_file_present("/app0/preamble-a") != 0;
    const bool ctl_preamble_b = cube_stop_file_present("/app0/preamble-b") != 0;
#else
    const bool ctl_pause = false, ctl_dump = false, ctl_nodepth = false, ctl_tex = false;
    const bool ctl_preamble_a = false, ctl_preamble_b = false;
#endif
    bool auto_rotate = !ctl_pause;
    bool opt_texture = ctl_tex;
    bool opt_depth = !ctl_nodepth;
#if GL_CUBE_HAVE_MESA_PREAMBLE
    if (ctl_preamble_a) {
        glSetHardwarePrelude(oops_mesa_preamble_a, (GLuint)(sizeof(oops_mesa_preamble_a) / sizeof(oops_mesa_preamble_a[0])));
        cube_klog("prelude: mesa preamble A (CONTEXT_CONTROL, CLEAR_STATE, radeonsi initial state)");
    } else if (ctl_preamble_b) {
        glSetHardwarePrelude(oops_mesa_preamble_b, (GLuint)(sizeof(oops_mesa_preamble_b) / sizeof(oops_mesa_preamble_b[0])));
        cube_klog("prelude: mesa preamble B (CONTEXT_CONTROL, radeonsi initial state, no CLEAR_STATE)");
    }
#else
    if (ctl_preamble_a || ctl_preamble_b) cube_klog("prelude: requested but this build has no oops-mesa preamble header");
#endif
    bool opt_lighting = true;
    bool opt_cull = true;
    if (opt_depth) glEnable(GL_DEPTH_TEST); else glDisable(GL_DEPTH_TEST);
    if (opt_texture) glEnable(GL_TEXTURE_2D);
    uint32_t last_frame_us = 0; /* the previous frame, top to swap, for the HUD */
    uint32_t prev_buttons = 0;
    uint64_t frame = 0;
    bool running = true;

#ifndef OOPS_HOST_BUILD
    cube_klog("entering 3D rendering loop at 60 FPS...");
#endif

    while (running) {
#ifndef OOPS_HOST_BUILD
        uint64_t t_top = oops_time_get_us(); /* frame phase timing, logged every 60 frames */
        uint64_t t_finish = 0, t_hash = 0, t_hud = 0;
#endif
        /* Poll DualSense controller */
        oops_pad_state_t pad;
        if (oops_input_poll(0, &pad) == 0 && pad.connected) {
            uint32_t pressed = pad.buttons & ~prev_buttons;
            prev_buttons = pad.buttons;

            /* Exit combo: L1 + R1 + OPTIONS or CIRCLE */
            if (((pad.buttons & OOPS_BUTTON_L1) &&
                 (pad.buttons & OOPS_BUTTON_R1) &&
                 (pad.buttons & OOPS_BUTTON_OPTIONS)) ||
                (pad.buttons & OOPS_BUTTON_CIRCLE) ||
                (pad.buttons & OOPS_BUTTON_OPTIONS)) {
#ifndef OOPS_HOST_BUILD
                cube_klog("exit combo received, terminating cleanly");
#endif
                running = false;
                break;
            }

            /* Toggle auto-rotation with CROSS */
            if (pressed & OOPS_BUTTON_CROSS) {
                auto_rotate = !auto_rotate;
            }

            /* Toggle Texture 2D with TRIANGLE */
            if (pressed & OOPS_BUTTON_TRIANGLE) {
                opt_texture = !opt_texture;
                if (opt_texture) glEnable(GL_TEXTURE_2D);
                else glDisable(GL_TEXTURE_2D);
            }

            /* Toggle Depth Test with SQUARE */
            if (pressed & OOPS_BUTTON_SQUARE) {
                opt_depth = !opt_depth;
                if (opt_depth) glEnable(GL_DEPTH_TEST);
                else glDisable(GL_DEPTH_TEST);
            }

            /* Toggle Lighting with L1 */
            if (pressed & OOPS_BUTTON_L1) {
                opt_lighting = !opt_lighting;
                if (opt_lighting) glEnable(GL_LIGHTING);
                else glDisable(GL_LIGHTING);
            }

            /* Toggle Culling with R1 */
            if (pressed & OOPS_BUTTON_R1) {
                opt_cull = !opt_cull;
                if (opt_cull) glEnable(GL_CULL_FACE);
                else glDisable(GL_CULL_FACE);
            }

            /* Cycle geometry mesh with R2 or L2 */
            if (pressed & (OOPS_BUTTON_R2 | OOPS_BUTTON_L2)) {
                geom_mode = (geom_mode_t)((geom_mode + 1) % GEOM_MAX);
            }

            /* Manual control: D-Pad / Analog sticks */
            if (pad.buttons & OOPS_BUTTON_LEFT)  rot_y -= 2.0f;
            if (pad.buttons & OOPS_BUTTON_RIGHT) rot_y += 2.0f;
            if (pad.buttons & OOPS_BUTTON_UP)    rot_x -= 2.0f;
            if (pad.buttons & OOPS_BUTTON_DOWN)  rot_x += 2.0f;
        } else {
            prev_buttons = 0;
        }

#ifndef OOPS_HOST_BUILD
        if ((frame % 30u) == 0u) {
            if (cube_stop_file_present(stop_path)) {
                cube_klog("stop file found, terminating cleanly");
                running = false;
                break;
            }
        }
#endif

#ifndef OOPS_HOST_BUILD
        if (ctl_dump && frame == 30u) glRequestHardwareDump(); /* this frame's stream becomes the oracle record */
        /* Paused runs toggle the depth test at frames 60 and 90, so the frames either side compare. */
        if (ctl_pause && (frame == 60u || frame == 90u)) {
            opt_depth = !opt_depth;
            if (opt_depth) glEnable(GL_DEPTH_TEST); else glDisable(GL_DEPTH_TEST);
        }
#endif

        if (auto_rotate) {
            rot_x += 0.75f;
            rot_y += 1.25f;
            rot_z += 0.50f;
            if (rot_x >= 360.0f) rot_x -= 360.0f;
            if (rot_y >= 360.0f) rot_y -= 360.0f;
            if (rot_z >= 360.0f) rot_z -= 360.0f;
        }

        /* 1. Clear Color and Depth Buffers */
        glClearColor(0.05f, 0.07f, 0.12f, 1.0f);
        glClearDepth(1.0);
        glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);

        /* 2. Setup Perspective Projection Matrix */
        glMatrixMode(GL_PROJECTION);
        glLoadIdentity();
        gluPerspective(45.0, 1920.0 / 1080.0, 0.1, 100.0);

        /* 3. Setup ModelView Matrix Stack */
        glMatrixMode(GL_MODELVIEW);
        glLoadIdentity();
        glTranslatef(0.0f, 0.0f, cam_dist);

        /* Set light in camera space before rotation so light remains stationary while cube rotates */
        glLightfv(GL_LIGHT0, GL_POSITION, light_pos);

        glRotatef(rot_x, 1.0f, 0.0f, 0.0f);
        glRotatef(rot_y, 0.0f, 1.0f, 0.0f);
        glRotatef(rot_z, 0.0f, 0.0f, 1.0f);

        /* 4. Render Active 3D Geometry */
        GLsizei vcount = 0;
        const char *geom_name = "CUBE";
        size_t tri_count = 12;

        switch (geom_mode) {
        case GEOM_CUBE:
            glVertexPointer(3, GL_FLOAT, 0, s_cube_vertices);
            glNormalPointer(GL_FLOAT, 0, s_cube_normals);
            glColorPointer(3, GL_FLOAT, 0, s_cube_colors);
            glTexCoordPointer(2, GL_FLOAT, 0, s_cube_texcoords);
            vcount = 36;
            geom_name = "CUBE";
            tri_count = 12;
            break;
        case GEOM_TORUS:
            if (torus_mesh.positions) {
                glVertexPointer(3, GL_FLOAT, 0, torus_mesh.positions);
                glNormalPointer(GL_FLOAT, 0, torus_mesh.normals);
                glColorPointer(3, GL_FLOAT, 0, torus_mesh.colors);
                glTexCoordPointer(2, GL_FLOAT, 0, torus_mesh.texcoords);
                vcount = (GLsizei)torus_mesh.vertex_count;
                geom_name = "TORUS";
                tri_count = torus_mesh.triangle_count;
            }
            break;
        case GEOM_SPHERE:
            if (sphere_mesh.positions) {
                glVertexPointer(3, GL_FLOAT, 0, sphere_mesh.positions);
                glNormalPointer(GL_FLOAT, 0, sphere_mesh.normals);
                glColorPointer(3, GL_FLOAT, 0, sphere_mesh.colors);
                glTexCoordPointer(2, GL_FLOAT, 0, sphere_mesh.texcoords);
                vcount = (GLsizei)sphere_mesh.vertex_count;
                geom_name = "SPHERE";
                tri_count = sphere_mesh.triangle_count;
            }
            break;
        default:
            break;
        }

        if (vcount > 0) {
            glDrawArrays(GL_TRIANGLES, 0, vcount);
        }
        glFinish();
#ifndef OOPS_HOST_BUILD
        t_finish = oops_time_get_us();
#endif
        (void)geom_name;
        (void)tri_count;

        /* Measured from the render target, console-side, after the fence and before the HUD or
         * the flip touch anything: a hash of every pixel, the count outside the clear colour,
         * and the centre pixel. The HDMI capture is lossy; this is not. */
        uint32_t *fb = oops_display_get_framebuffer(disp);
        const uint32_t *src = fb;
#ifndef OOPS_HOST_BUILD
        /* The CP's cached copy of the target: the target itself is uncached for the CPU and a full
         * read of it drops the demo to two frames a second. */
        const GLuint *rb = glGetFrameReadback();
        if (rb) src = rb;
        uint64_t hash_t0 = oops_time_get_us();
#endif
        uint32_t center_pix = 0;
        uint32_t mod_pixels = 0;
        uint32_t frame_hash = 0x811c9dc5u; /* FNV-1a, 32-bit, over all 1920 x 1080 words */
        if (src) {
            center_pix = src[540 * 1920 + 960];
            for (size_t p = 0; p < (size_t)1920 * 1080; p++) {
                uint32_t v = src[p];
                if (v != 0xff0d121fu) mod_pixels++;
                frame_hash ^= v;
                frame_hash *= 0x01000193u;
            }
        }
#ifndef OOPS_HOST_BUILD
        t_hash = oops_time_get_us();
        if (frame == 1u || (frame % 300u) == 0u) cube_klog_hex("hash-us", (uint32_t)(oops_time_get_us() - hash_t0));
        if (ctl_pause || ctl_dump) {
            if (frame < 300u || (frame % 60u) == 0u) cube_klog_hex("frame-hash", frame_hash);
            if (frame == 0u) {
                cube_klog_hex("frame-rot-x-deg", (uint32_t)(int32_t)rot_x);
                cube_klog_hex("frame-rot-y-deg", (uint32_t)(int32_t)rot_y);
                cube_klog_hex("frame-rot-z-deg", (uint32_t)(int32_t)rot_z);
            }
            if (ctl_dump && frame == 30u) {
                cube_klog_hex("oracle-hash", frame_hash);
                cube_klog_hex("oracle-mod-pixels", mod_pixels);
                cube_klog_hex("oracle-center-pixel", center_pix);
                cube_klog_hex("oracle-depth-on", opt_depth ? 1u : 0u);
                cube_klog_hex("oracle-cull-on", opt_cull ? 1u : 0u);
            }
            if (ctl_pause && src && !s_prev_frame) s_prev_frame = (uint32_t *)oops_mem_alloc((size_t)1920 * 1080 * 4, 64, OOPS_MEM_WB_ONION);
            if (ctl_pause && src && s_prev_frame) {
                /* The frame after a depth toggle against the frame before it, pixel for pixel. */
                if (frame == 61u || frame == 91u) {
                    uint32_t diff = 0;
                    for (size_t p = 0; p < (size_t)1920 * 1080; p++) {
                        if (src[p] != s_prev_frame[p]) diff++;
                    }
                    cube_klog_hex(opt_depth ? "depth-on-minus-off-pixels" : "depth-off-minus-on-pixels", diff);
                }
                memcpy(s_prev_frame, src, (size_t)1920 * 1080 * 4);
            }
        }
#endif
        if (fb) {
#if defined(__x86_64__)
            __builtin_ia32_clflush((const void *)&fb[540 * 1920 + 960]);
            for (size_t p = 0; p < (size_t)1920 * 1080; p += 64) {
                __builtin_ia32_clflush((const void *)&fb[p]);
            }
#endif
            center_pix = fb[540 * 1920 + 960];
            for (size_t p = 0; p < (size_t)1920 * 1080; p += 64) {
                if (fb[p] != 0xff0d121fu) {
                    mod_pixels++;
                }
            }
        }

        /* 5. Render 2D Telemetry & Diagnostics HUD */
        oops_surface_t surf = oops_display_get_surface(disp);

        /* Outer high-contrast framing borders (12px) */
        oops_draw_rect(&surf, 0, 0, 1920, 12, OOPS_COLOR_CYAN);
        oops_draw_rect(&surf, 0, 1068, 1920, 12, OOPS_COLOR_CYAN);
        oops_draw_rect(&surf, 0, 0, 12, 1080, OOPS_COLOR_CYAN);
        oops_draw_rect(&surf, 1908, 0, 12, 1080, OOPS_COLOR_CYAN);

        /* Header banner panel */
        oops_draw_rect_blend(&surf, 40, 30, 820, 260, 0xd008101cu);
        oops_draw_rect(&surf, 40, 30, 820, 3, OOPS_COLOR_CYAN);

        oops_draw_text(&surf, 60, 48, "OOPS-GL 2.0: 3D MULTI-MESH (RDNA2)", OOPS_COLOR_WHITE, 2);
        oops_draw_text(&surf, 60, 75, "RDNA2 Freestanding Translation Layer", 0xff66ccffu, 1);
        oops_draw_text(&surf, 60, 96, "Target: Prospero/Trinity (FW 12.40)", 0xffaaaaaau, 1);
        /* The badge is a measurement, asked of the context every frame: the GPU-only clear test
         * at start-up plus the last submission's end-of-pipe fence and GPU clock. */
        gl_hw_status_t hw;
        memset(&hw, 0, sizeof(hw));
#ifndef OOPS_HOST_BUILD
        glGetHardwareStatus(&hw);
#endif
        uint32_t badge_col = hw.verified ? 0xff44ff88u : (hw.failed ? 0xffff5544u : 0xffffcc44u);
        oops_draw_text(&surf, 640, 48, hw.verified ? "GPU" : (hw.failed ? "GPU FAILED" : "GPU ?"), badge_col, 2);
        {
            char hwline[128];
            char hx[16];
            int hl = 0;
            if (hw.verified) {
                hl = cube_append(hwline, hl, "GPU verified: clear test ");
                int_to_str((int)hw.clear_matched, hx); hl = cube_append(hwline, hl, hx);
                hl = cube_append(hwline, hl, "/");
                int_to_str((int)hw.clear_expected, hx); hl = cube_append(hwline, hl, hx);
                hl = cube_append(hwline, hl, ", fence ");
                hex_to_str(hw.fence, hx); hl = cube_append(hwline, hl, hx);
                hl = cube_append(hwline, hl, ", clock ");
                hex_to_str(hw.timestamp_hi, hx); hl = cube_append(hwline, hl, hx);
                hex_to_str(hw.timestamp_lo, hx); hl = cube_append(hwline, hl, hx + 2);
            } else if (hw.failed) {
                hl = cube_append(hwline, hl, "GPU FAILED: ");
                hl = cube_append(hwline, hl, hw.failure ? hw.failure : "unknown");
                hl = cube_append(hwline, hl, ". Nothing is drawn.");
            } else {
                hl = cube_append(hwline, hl, "GPU unverified: no confirmed frame yet");
            }
            oops_draw_text(&surf, 60, 116, hwline, badge_col, 1);
        }

        /* Canaries */
        char h_vs[16], h_ps[16];
        GLuint can_vs = 0, can_ps = 0, can_vs_s0 = 0, can_ps_s0 = 0;
#ifndef OOPS_HOST_BUILD
        glGetCanaryEx(&can_vs, &can_ps, &can_vs_s0, &can_ps_s0);
#endif
        hex_to_str(can_vs, h_vs);
        hex_to_str(can_ps, h_ps);

        char stat_buf[128];
        char num_buf[16];

        /* VS & PS Canary row */
        memcpy(stat_buf, "VS Can: ", 8);
        int sl = 8;
        for (int i = 0; h_vs[i]; i++) stat_buf[sl++] = h_vs[i];
        memcpy(&stat_buf[sl], "  |  PS Can: ", 13);
        sl += 13;
        for (int i = 0; h_ps[i]; i++) stat_buf[sl++] = h_ps[i];
        stat_buf[sl] = '\0';
        oops_draw_text(&surf, 60, 138, stat_buf, (can_vs == 0xbeef0001u) ? OOPS_COLOR_GREEN : OOPS_COLOR_YELLOW, 1);

        /* Frame hash, pixels outside the clear colour, centre pixel: the render target's own numbers */
        {
            char hx[16];
            sl = cube_append(stat_buf, 0, "Hash: ");
            hex_to_str(frame_hash, hx); sl = cube_append(stat_buf, sl, hx);
            sl = cube_append(stat_buf, sl, "  |  Mod Pix: ");
            int_to_str((int)mod_pixels, num_buf); sl = cube_append(stat_buf, sl, num_buf);
            sl = cube_append(stat_buf, sl, "  |  Center: ");
            hex_to_str(center_pix, hx); sl = cube_append(stat_buf, sl, hx);
            oops_draw_text(&surf, 60, 160, stat_buf, (mod_pixels > 0) ? OOPS_COLOR_GREEN : OOPS_COLOR_RED, 1);
        }

        /* Pipeline State switches */
        oops_snprintf(stat_buf, sizeof(stat_buf), "Cull: %s | Light: %s | Tex: %s | Depth: %s",
                      opt_cull ? "ON(CCW)" : "OFF",
                      opt_lighting ? "ON" : "OFF",
                      opt_texture ? "ON" : "OFF",
                      opt_depth ? "ON" : "OFF");
        oops_draw_text(&surf, 60, 182, stat_buf, OOPS_COLOR_CYAN, 1);

        /* Rotation & Frame telemetry */
        oops_snprintf(stat_buf, sizeof(stat_buf), "RotX: %d deg  RotY: %d deg  |  Frame: %u (%u ms/frame)%s",
                      (int)rot_x, (int)rot_y, (unsigned int)frame,
                      (unsigned int)(last_frame_us / 1000u),
                      !auto_rotate ? "  PAUSED" : "");
        oops_draw_text(&surf, 60, 204, stat_buf, OOPS_COLOR_WHITE, 1);

        /* Geometry & Complexity telemetry */
        oops_snprintf(stat_buf, sizeof(stat_buf), "Mesh: %s  |  Tris: %u  |  Verts: %u",
                      geom_name, (unsigned int)tri_count, (unsigned int)vcount);
        oops_draw_text(&surf, 60, 226, stat_buf, 0xffffaa33u, 1);

        /* Footer controls banner */
        oops_draw_rect_blend(&surf, 40, 1000, 1100, 50, 0xd008101cu);
        oops_draw_rect(&surf, 40, 1000, 1100, 2, 0xff335577u);
        oops_draw_text(&surf, 60, 1018,
                       "Controls: D-Pad=Orbit | [X]=Rotate | [R2]=Mesh | [/\\ ]=Tex | [][]=Depth | [L1]=Light | [R1]=Cull | (O)=Exit",
                       0xffeeeeeeu, 1);

#ifndef OOPS_HOST_BUILD
        t_hud = oops_time_get_us();
#endif
        /* 6. Present Frame */
        glSwapBuffers();
#ifndef OOPS_HOST_BUILD
        {
            uint64_t t_end = oops_time_get_us();
            last_frame_us = (uint32_t)(t_end - t_top);
        }
        /* The GPU clock the end-of-pipe event writes, against the CPU clock: its rate is data. */
        if (frame == 5u || frame == 35u) {
            static uint64_t clk0 = 0, us0 = 0;
            gl_hw_status_t st;
            glGetHardwareStatus(&st);
            uint64_t clk = ((uint64_t)st.timestamp_hi << 32) | st.timestamp_lo;
            uint64_t us = oops_time_get_us();
            if (frame == 5u) { clk0 = clk; us0 = us; }
            else if (us > us0) {
                cube_klog_hex("gpu-clock-delta-lo", (uint32_t)(clk - clk0));
                cube_klog_hex("cpu-us-delta", (uint32_t)(us - us0));
                cube_klog_hex("gpu-clock-per-us", (uint32_t)((clk - clk0) / (us - us0)));
            }
        }
        if (frame == 5u || (frame % 60u) == 0u) {
            uint64_t t_end = oops_time_get_us();
            last_frame_us = (uint32_t)(t_end - t_top);
            cube_klog_hex("t-draw-finish-us", (uint32_t)(t_finish - t_top));
            cube_klog_hex("t-hash-us", (uint32_t)(t_hash - t_finish));
            cube_klog_hex("t-hud-us", (uint32_t)(t_hud - t_hash));
            cube_klog_hex("t-swap-us", (uint32_t)(t_end - t_hud));
        }
#endif

        frame++;
    }

    /* Clean up */
    oops_mesh_free(&torus_mesh);
    oops_mesh_free(&sphere_mesh);
    glDeleteTextures(1, &tex_id);
    glContextDestroy(gl_ctx);
    oops_display_close(disp);

#ifndef OOPS_HOST_BUILD
    cube_klog("gl-cube session closed cleanly");
#endif
    return 0;
}
